site_name: QA Test Management System
site_url: https://droppii.github.io/qa-tms/
repo_url: https://github.com/droppii/qa-tms
repo_name: droppii/qa-tms

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags
  - git-revision-date

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Test Cases:
    - Overview: test-cases/index.md
    - Authentication:
      - Login: test-cases/functional/login.md
    - Gift Management:
      - View List: test-cases/gift/view-list.md
  - Test Suites:
    - Overview: test-suites/index.md
    - Gift PDP: test-suites/gift-pdp.md
  - Shared Steps:
    - Overview: shared-steps/index.md
    - Navigation: shared-steps/navigation.md
  - Guidelines:
    - Test Case Numbering: guidelines/test-case-numbering.md
